---
- name: Copy the appropriate kube-controller-manager and kube-scheduler kubeconfig files to each controller instance
  gather_facts: no
  become: true
  hosts: controllers

  tasks:

  - name: Copy the appropriate kube-controller-manager and kube-scheduler kubeconfig files to each controller instance
    copy:
      src: "{{ item }}"
      dest: "/home/vagrant/{{ item }}"
      owner: vagrant
      group: vagrant
    with_items:
      - admin.kubeconfig
      - kube-controller-manager.kubeconfig
      - kube-scheduler.kubeconfig
