---
version: '3.5'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    container_name: fluent
    networks:
      - redditnet
    ports:
      - '24224:24224'
      - '24224:24224/udp'

  elasticsearch:
    image: elasticsearch:6.7.1
    container_name: elastic
    networks:
      - redditnet
    expose:
      - 9200
    ports:
      - '9200:9200'

  kibana:
    image: kibana:6.7.1
    container_name: kibana
    networks:
      - redditnet
    ports:
      - '5601:5601'

networks:
  redditnet: