---
version: '3.5'
services:
  post_db:
    image: mongo:latest
    volumes:
      - post_db:/data/db
    networks:
      redditnet:
        aliases:
          - comment_db
          - post_db

  ui:
    image: ${USERNAME}/ui:${TAG}
    ports:
      - ${ext_port}:${int_port}/tcp
    networks:
      - redditnet

  post:
    image: ${USERNAME}/post:$TAG
    networks:
      redditnet:
        aliases:
          - post

  comment:
    image: ${USERNAME}/comment:$TAG
    networks:
      redditnet:
        aliases:
          - comment

volumes:
  post_db:

networks:
  redditnet:
