---
version: '3.5'
services:
  post_db:
    image: mongo:latest
    volumes:
      - post_db:/data/db
    networks:
      redditnet:
        aliases:
          - comment_db
          - post_db

  ui:
    image: ${USER_NAME}/ui:${TAG}
    ports:
      - ${ext_port}:${int_port}/tcp
    networks:
      - redditnet
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:$TAG
    networks:
      redditnet:
        aliases:
          - post
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:$TAG
    networks:
      redditnet:
        aliases:
          - comment

volumes:
  post_db:

networks:
  redditnet:
